# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - alvinmdj
    assignees:
      - alvinmdj
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
     # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
